### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot set properties of null (setting 'anchor')

### ISSUE THREAD

**Issue by ca-d** [OpenEnergyTools/scl-substation-editor#1]
This happens any time I open our original sample file. Apparently, some custom element derived from base-substation-element-editor does not actually render the "addMenu", because that's the query result on which `updated` tries to set the `anchor`.

**Comment by ca-d** [comment]
My suggestion would be to do the rendering of the menu directly in the base-substation-element-editor and not in the derived class. Alternatively, one could change `updated` to contain

```ts
if (this.addMenu) this.addMenu.anchor = <HTMLElement>this.addButton;
```

and declare the query property optional

```ts
@query('mwc-menu') addMenu?: Menu;
```

**Comment by JakobVogelsang** [comment]
Should be fixed now. Thank you for spotting @ca-d my loved one.

**Comment by ca-d** [comment]
Thanks for fixing this!
