### ISSUE TITLE
Cannot create LNodes and other items

### ISSUE THREAD

**Issue by danyill** [OpenEnergyTools/scl-substation-editor#2]
I have recently been trying to create LNodes within the Substation Editor.

See the attached file:

[project (1).zip](https://github.com/OpenEnergyTools/scl-substation-editor/files/13211179/project.1.zip)

![image](https://github.com/OpenEnergyTools/scl-substation-editor/assets/674783/1fbeceac-081e-40bf-abd0-18e1c9145078)

When I click on any of the following:

* Text 
* Private
* LNode
* ConnectivityNode

I only see an XML editor:

![image](https://github.com/OpenEnergyTools/scl-substation-editor/assets/674783/f98fea23-87ea-4045-be55-f48a08713e9a)

For my present purposes I would like to be able to add an LNode to a Function

**Comment by jarradraumati** [comment]
To expand on this. I would like to be able to create an LNode within a Function, from a list of existing LNs within instantiated IEDs.

**Comment by JakobVogelsang** [comment]
@jarradraumati @danyill it should be possible now. Sorry for the delay, I have done quite some refactoring with this wizard.

**Comment by JakobVogelsang** [comment]
You can test on [scl-editor](https://openenergytools.github.io/scl-editor)

**Comment by jarradraumati** [comment]
Creating LNodes works a treat. Thank you @JakobVogelsang.
